### ISSUE TITLE
OBS: vl2 don't appear, vst has no UI

### ISSUE THREAD

**Issue by ewbteewbte** [DISTRHO/DPF-Plugins#16] opened 2020-08-29 10:48 UTC
So VST do make changes to the sound but there is no UI, only black window.
I did try the release version 1.3 and 1.2, also tried to compile from source with the same result.
PopOS 20.04

**Comment by falkTX** [comment] 2020-08-29 10:50
you mean lv2 version not appearing? likely OBS does not have all required features.

are you able to get the UI working with other hosts?

**Comment by ewbteewbte** [comment] 2020-08-29 10:52
well I use LSP vl2 plugins. they work great and VST like Tal-reverb work just fine. The only other host I have is Audacity, but no luck there too

**Comment by falkTX** [comment] 2020-08-29 10:54
Try carla or jalv then, they are very simple hosts (compared to full-fledged daws)
We need to know if the issue is on the plugin side, or the system.

The DPF plugins use OpenGL for the UI, so the issue could be there.
Working opengl support is needed in order to show the UIs.

**Comment by ewbteewbte** [comment] 2020-08-29 10:56
Thanks, I will try now. Also Calf plugins miss the UI as well, while they appear to make changes to the input/output.

**Comment by falkTX** [comment] 2020-08-29 10:57
calf uses gtk2 for their UIs, I doubt OBS supports that.

**Comment by ewbteewbte** [comment] 2020-08-29 11:06
it works with Carla, thank you so much, now I need to learn how to use jack as well. I switched to linux just this year and it is awesome, but sometimes hard :)

**Comment by falkTX** [comment] 2021-09-19 14:15
Forgot to close this ticket, doing that now.

**Closed by falkTX** 2021-09-19 14:15 UTC
